[*]
wallpaper_mode=crop
wallpaper=/opt/smashdeck/dashboard/static/img/fox-hunter.jpg
desktop_bg=#07060f
desktop_fg=#b8ff2a
desktop_shadow=#07060f
desktop_font=Piboto 11
show_documents=0
show_trash=0
show_mounts=0
show_wm_menu=0
